version: '3'

services: 
  mysql:
    container_name: user-gallery-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: user_gallery
      MYSQL_ROOT_PASSWORD: 123456
    ports:
    - "3306:3306"
    restart: always
    
  app:
    container_name: user-gallery-app
    image: berberoglucan/user-gallery-demo
    expose:
      - "8080:8080"
    restart: always
    expose:
      - "8080"
    command: java -jar user-gallery.jar
    depends_on:
      - mysql